--- 
apiVersion: "apps/v1"
kind: "Deployment"
metadata: 
  name: "hqcloud-iams"
  namespace: "kube-system"
  labels: 
    name: "hqcloud-iams"
spec: 
  replicas: 1
  selector: 
    matchLabels:
      name: "hqcloud-iams"
  template: 
    metadata: 
      labels: 
        name: "hqcloud-iams"
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      containers:
      - name: "iams"
        image: "registry.hqcloud.com.cn:5000/hqcloud/dynastie-iams:1.0"
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 8080
        env:
        - name: "DATASOURCE_URL"
          value: "jdbc:mysql://hqcloud-database.kube-system:3306/dynastie_iams?useUnicode=
true&characterEncoding=utf8&characterSetResults=utf8"
        - name: "DATASOURCE_USERNAME"
          value: "root"
        - name: "DATASOURCE_PASSWORD"
          value: "multifort"
---
apiVersion: v1
kind: Service
metadata:
  name: hqcloud-iams
  namespace: kube-system
  labels: 
    name: hqcloud-iams
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: iams-port
    nodePort: 32051
  selector:
    name: hqcloud-iams
