--- 
apiVersion: "apps/v1"
kind: "Deployment"
metadata: 
  name: "hqcloud-keycloak"
  namespace: "kube-system"
  labels: 
    name: "hqcloud-keycloak"
spec: 
  replicas: 1
  selector: 
    matchLabels:
      name: "hqcloud-keycloak"
  template: 
    metadata: 
      labels: 
        name: "hqcloud-keycloak"
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      containers:
      - name: "keycloak"
        image: "registry.hqcloud.com.cn:5000/hqcloud/keycloak:8.0.1"
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 8080
        env:
        - name: "JAVA_OPTS"
          value: "-Dkeycloak.profile.feature.scripts=enabled -Dkeycloak.profile.feature.upload_scripts=enabled -server -Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true"
        - name: "KEYCLOAK_USER"
          value: "admin"
        - name: "KEYCLOAK_PASSWORD"
          value: "admin"
        - name: "DB_VENDOR"
          value: "MARIADB"
        - name: "DB_ADDR"
          value: "hqcloud-database.kube-system"
        - name: "DB_PORT"
          value: "3306"
        - name: "DB_DATABASE"
          value: "keycloak"
        - name: "DB_USER"
          value: "root"
        - name: "DB_PASSWORD"
          value: "multifort"
        - name: "KEYCLOAK_IMPORT"
          value: "/tmp/keycloak-realm.json"
        volumeMounts:
        - name: "realm"
          mountPath: "/tmp/keycloak-realm.json"
      volumes:
      - name: "realm"
        hostPath:
          path: "/opt/hqcloud/configs/keycloak-import.json"
---
apiVersion: v1
kind: Service
metadata:
  name: hqcloud-keycloak
  namespace: kube-system
  labels: 
    name: hqcloud-keycloak
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: keycloak-port
    nodePort: 31080
  selector:
    name: hqcloud-keycloak
